name: Tests

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  integration-test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository }}:lsst-w_2024_34
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root

    steps:
      - name: Checkout proc-decam (with LFS)
        uses: actions/checkout@v4
        with:
          path: proc_decam
          lfs: true

      - name: Checkout kbmod_imdiff_recipe (with LFS)
        uses: actions/checkout@v4
        with:
          repository: dirac-institute/kbmod_imdiff_recipe
          path: kbmod_imdiff_recipe
          lfs: true
          ref: main

      - name: Checkout kbmod_mastercals_recipe (with LFS)
        uses: actions/checkout@v4
        with:
          repository: dirac-institute/kbmod_mastercals_recipe
          path: kbmod_mastercals_recipe
          lfs: true
          ref: main
          
      - name: Run pipeline
        shell: bash
        run: |
          source /opt/lsst/software/stack/loadLSST.bash
          setup lsst_distrib
          set -xeuo pipefail

          export WORK=$(pwd)
          # install checked out software
          python -m pip install ${WORK}/proc_decam
          
          # change ownership of work directory
          chown -R lsst:lsst ${WORK}

          # switch to lsst user
          su lsst <<EOF
            source /opt/lsst/software/stack/loadLSST.bash
            setup lsst_distrib
            set -xeuo pipefail

            # set up data
            python ${WORK}/proc_decam/tests/make_exposures.py \
            --mastercals-dir ${WORK}/kbmod_mastercals_recipe/trimmedRawData/210318/calib \
            --science-dir ${WORK}/kbmod_imdiff_recipe/trimmedRawData/210318/science \
            --output ${DATA}/exposures.ecsv \
            --image-dir ${DATA}/images

            # start repo
            proc-decam db start ${REPO}
            
            # Ingest refcats
            proc-decam refcats ${REPO} ${DATA}/exposures.ecsv
            
            # ingest fakes
            cd ${WORK}/kbmod_imdiff_recipe/trimmedRawData/fakes
            python create_fakes.py
            cd ${WORK}
            
            proc-decam fakes ${REPO} \
              ${WORK}/kbmod_imdiff_recipe/trimmedRawData/fakes/fakes_fakeSrcCat.fits \
              --format fits

            # ingest and process bias
            proc-decam ingest ${DATA}/exposures.ecsv -b ${REPO} --image-dir ${DATA}/images/
            proc-decam raw ${REPO} bias 20210318
            proc-decam collection ${REPO} bias 20210318          
            
            cd ${WORK}/proc_decam # must have proc-decam pipelines available
            proc-decam execute ${REPO} 20210318/bias \
              --pipeline pipelines/bias.yaml#step1 \
              --where "instrument='DECam' and detector=35"
          EOF          
